apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: managed-serviceaccount-addon-manager
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      open-cluster-management.io/addon: managed-serviceaccount
  template:
    metadata:
      labels:
        open-cluster-management.io/addon: managed-serviceaccount
    spec:
      serviceAccount: managed-serviceaccount
      securityContext:
        {{- if semverCompare ">=4.11.0" .Values.hubconfig.ocpVersion }} 
        seccompProfile: 
          type: RuntimeDefault
        {{- end }}
      containers:
        - name: manager
          image: {{ .Values.image }}:{{ .Values.tag | default (print "v" .Chart.Version) }}
          imagePullPolicy: IfNotPresent
          command:
            - /manager
          args:
            - --leader-elect=true
            - --agent-image-name={{ .Values.image }}:{{ .Values.tag | default (print "v" .Chart.Version) }}
            - --agent-install-all={{ .Values.agentInstallAll }}
            {{- if .Values.featureGates }}
            - --feature-gates=EphemeralIdentity={{ .Values.featureGates.ephemeralIdentity | default false}}
            {{- end}}
            {{- if .Values.agentImagePullSecret }}
            - --agent-image-pull-secret={{ .Values.agentImagePullSecret }}
            {{- end}}
